### ISSUE TITLE
wtb readme.md

### ISSUE THREAD

**Issue by SnooperXP** [TerrorBite/textgame#1]
readme.md plz

**Comment by TerrorBite** [comment]
Will work on one. Currently the project is very much a work in progress, ideas and documentation are jotted down in textgame.txt and it doesn't even have a proper name.

**Comment by shazow** [comment]
All the more reason for a README—Write us about your ambitions, your desires, your goals, your dreams and what you had for breakfast. Also a license.

**Comment by TerrorBite** [comment]
A basic readme has been put in place, while documentation is being ported over to Markdown in the /docs folder.

License - thinking about MIT, since this project is something I care about a little (otherwise I'd probably put it under WTFPL).

**Comment by TerrorBite** [comment]
This is long since complete at this point.
